<?php

namespace kiraxe\AdminCrmBundle\Repository;

/**
 * BodyTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BodyTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
