<?php

namespace kiraxe\AdminCrmBundle\Repository;

/**
 * ClienteleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClienteleRepository extends \Doctrine\ORM\EntityRepository
{
}
