<?php

namespace kiraxe\AdminCrmBundle\Repository;

/**
 * ExpensesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExpensesRepository extends \Doctrine\ORM\EntityRepository
{
}
