<?php

namespace kiraxe\AdminCrmBundle\Repository;

/**
 * ManagerPercentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ManagerPercentRepository extends \Doctrine\ORM\EntityRepository
{
}
