<?php

namespace kiraxe\AdminCrmBundle\Repository;

/**
 * ManagerOrdersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ManagerOrdersRepository extends \Doctrine\ORM\EntityRepository
{
}
