<?php

namespace kiraxe\AdminCrmBundle\Repository;

/**
 * MaterialsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MaterialsRepository extends \Doctrine\ORM\EntityRepository
{
}
