<?php

namespace kiraxe\AdminCrmBundle\Repository;

/**
 * WorkerServiceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WorkerServiceRepository extends \Doctrine\ORM\EntityRepository
{
}
