<?php

namespace kiraxe\AdminCrmBundle\Repository;

/**
 * WorkersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WorkersRepository extends \Doctrine\ORM\EntityRepository
{
}
